### ISSUE TITLE
Arriving to set up

### ISSUE THREAD

**Issue by philnash** [berlinjs/jsconf2017-special#6]
Hi! What's the best time to arrive at the venue to tech check? Is 7 ok, or should I get there a bit before?

**Comment by rmehner** [comment]
Guess a little before 7 (like 6:45) should be fine.

What's the computer you are using and what connectors do you have?

**Comment by philnash** [comment]
I have a MacBook Pro with an HDMI port and connectors for VGA/DVI to MiniDisplayPort. It's normally fine to connect to anything. I just like to make sure!

**Comment by rmehner** [comment]
Should be fine. We're gonna be there at 5:30pm the latest for setup.
